function MATSEDLAB
tic;                        %start timing
clear all;                  %clear memory
close all;                  %close existing plots

global SimValues sol NumVars;
global para;                %declare the temporary variable para to read the parameters from the input file

fid = fopen('para.in','r'); %reading the parameters from para.in
C = textscan(fid,'%s%f');   %names of parameters, values of parameters
para = C{2};                %we only need the values of parameters
fclose(fid);                %close file

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%BLOCK ONE%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%***** USER DEFINED *****%
x = linspace(0,15,511);         % definition of the spatial domain, x=[0 15] cm with resolution of 511
t = linspace(0,400,401);        % definition of the time domain, t=[0 400] years with resolution of 401
% defining the species
VarNames = {'O2(aq)',...        %u1
            'Fe(OH)3(s)',...    %u2
            'FeOOH(s)', ...     %u3
            'SO4(2-)(aq)', ...  %u4
            'Fe(2+)(aq)', ...   %u5
            'S(-II)(aq)',...    %u6
            'FeS(s)',...        %u7
            'S(0)(aq)',...      %u8
            'S8(s)',...         %u9
            'FeS2(s)',...       %u10
            'OMS(s)',...        %u11
            'OM1(s)',...        %u12
            'OM2(s)',...        %u13
            'OMSO(s)',...		%u14
			'AsFea(s)',...		%u15
			'AsFeb(s)',...		%u16
			'AsFe2(s)',...		%u17
			'AsO4(aq)',...		%u18
			'PO4(aq)',...		%u19
			'PO4adsa(s)',...	%u20
			'PO4adsb(s)',...	%u21
			'Ca2(aq)',...		%u22
			'CaPO4(s)',...      %u23
            'NO3(aq)',...       %u24
            'NH4(aq)'};%u25
NumVars = int16(length(VarNames)) ;

SimValues = cell(NumVars, 1);                       %creates an NumVars-by-1 cell array of empty matrices
                                                    %to store the concentration
rt_time = clock;                                    %display starting time
fprintf('\nThe starting time is %.0f/%.0f/%.0f %.0f:%.0f:%.0f\n', rt_time(1),...
    rt_time(2), rt_time(3), rt_time(4), rt_time(5), rt_time(6));

disp('solving PDE ');
sol = pdepe(0,@pdex14pde,@pdex1ic,@pdex1bc,x,t);    %calls the solver and stores the result in 'sol'
toc;                                                %stop timing

rt_time = clock;                                    %display ending time
fprintf('The ending time is %.0f/%.0f/%.0f %.0f:%.0f:%.0f\n', rt_time(1),...
    rt_time(2), rt_time(3), rt_time(4), rt_time(5), rt_time(6));

for j = 1:NumVars
    SimValues{j} = sol(:,:,j);                      %store the solution in the cell,
end                                                 %cleaner as compared to the sol matrix

save('Result.mat','SimValues','sol','para');        %save the result in Result.mat

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%BLOCK TWO%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [c,f,s] = pdex14pde(x,t,u,DuDx)
global BC0_O2 BC0_FeOH3 BC0_FeOOH BC0_SO4 BC0_Fe BC0_H2S BC0_FeS BC0_S0...
       BC0_S8 BC0_FeS2 BC0_OMS BC0_OM1 BC0_OM2 BC0_OMSO BC0_AsFea BC0_AsFeb...
       BC0_AsFe2 BC0_AsO4 BC0_PO4 BC0_PO4adsa BC0_PO4adsb BC0_Ca2 BC0_CaPO4...
       BC0_NO3 BC0_NH4 w F NumVars;
global para;
%***** USER DEFINED *****%
%boundary conditions at sediment-water interface---------------------------
BC0_O2 = 0.152;
BC0_FeOH3 = 6.7;
BC0_FeOOH = 4.6;
BC0_SO4 = 0.02;  %SO4 peaks at 389th year
BC0_Fe = 0; 
BC0_H2S = 0; 
BC0_FeS = 0;
BC0_S0 = 0;
BC0_S8 = 0;
BC0_FeS2 = 0;
BC0_OMS = 0;
BC0_OM1 = 250;
BC0_OM2 = BC0_OM1*0.5;
BC0_OMSO = BC0_OM2*0.0045;
fAsFe = 1e-6;                         %Amount of As associated with Fe
BC0_AsFea = BC0_FeOH3*fAsFe;
BC0_AsFeb = BC0_FeOOH*fAsFe;
BC0_AsFe2 = BC0_FeOH3*fAsFe;
BC0_AsO4 = 3e-4;
BC0_PO4 = 3e-4;
fPFe = 1e-6;
BC0_PO4adsa = BC0_FeOH3*fPFe;
BC0_PO4adsb = BC0_FeOOH*fPFe;
BC0_Ca2 = 4e-2;
BC0_CaPO4 = 0;
BC0_NO3 = 0.0087;
BC0_NH4 = 0;
%bioturbatiuon coef--------------------------------------------------------
D_bio = 0.0694;
%molecular diffusion coefs-------------------------------------------------
D_O2 = 375; 
D_SO4 = 175;
D_Fe = 118;
D_H2S = 284;
D_S0 = 100;
D_AsO4 = 160;
D_PO4 = 232;
D_Ca2 = 212;
D_NO3 = 508;
D_NH4 = 530;
%xyz ratio-----------------------------------------------------------------
Cx1 = para(1);              %each value has been replaced with the
Ny1 = para(2);              %corresponding entry in 'para'
Pz1 = para(3);
Cx2 = para(4);
Ny2 = para(5);
Pz2 = para(6);
%half saturation coefs-----------------------------------------------------
KO2 = para(7);          
KNO3 = para(8);                
KFeOH3 = para(9);               
KFeOOH = para(10);
KSO4 = para(11);
%inhibition coefs----------------------------------------------------------
kinO2 = para(12);     
kinNO3 = para(13);    
kinFeOH3 = para(14);
kinFeOOH = para(15);
kinSO4 = para(16);
%saturation constants------------------------------------------------------
KFeS = para(17);
%Secondary reaction constants----------------------------------------------
kOM1 = 1;                           %degredation rate constant for OM1, Rc1
kOM2 = 0.01;                        %degredation rate constant for OM2, Rc2
ktsox = para(18);                   %S(II) oxidation by O2, R5
ktsfe = para(19);                   %Fe(OH)3 reduction by S2-, R6
kfeox = para(20);                   %Fe(II) oxidation by O2, R7
kfedis = para(21);                  %dissolution rate of FeS, R8
kfepre = para(22);                  %precipitation rate of FeS, R_8
ksorg = para(23);                   %Sulfidization of OM, R9
krhom = para(24);                   %S8 formation, R10
kpyrpre = para(25);                 %Pyrite precipitation, R11
kSdis = para(26);                   %Elemental sulfur dissolution, R12
kSpre = para(27);                   %Elemental sulfur precipitation, R_12
komso = para(28);                   %OMSO hydrolysis, R13
kOMS = para(29);                    %Formation of OMS from SO4 directly, R14
kAsO4_adsa = para(30);              %As sorption onto Fe(OH)3, R15
kAsO4_adsb = para(31);              %As sorption onto FeOOH, R16
kAs_FeS = para(32);                 %As sorption onto FeS, R17
kAs_FeS2 = para(33);                %As sorption onto FeS2, R18
k_psorb_a = para(34);               %PO4 sorption onto Fe(OH)3, R22
k_psorb_b = para(35);               %PO4 sorption onto FeOOH, R23
kapa = para(36);                    %Apatite precipitation, R25
k_apa = para(37);
knh4ox = para(38);

%other parameters----------------------------------------------------------
w = 0.1;                                %time-dependant burial rate
alfa0 = 14.4;                           %bioirrigation constant at sediment-water interface
alfax = alfa0*exp(-0.25*x);             %depth-dependant bioirrigation
h_plus = 3.4e-4;                        %[H+] concentration, equals 10^(-pH)
F = 0.06;                               %convertion factor=rhob*(1-fi)/fi; where fi=porosity and rhob=solid phase density

%indices-------------------------------------------------------------------
fO2 = u(1)/(KO2+u(1));
fNO3 = u(24)/(KNO3+u(24))*kinO2/(kinO2+u(1));
fFeOH3 = u(2)/(KFeOH3+u(2))*kinO2/(kinO2+u(1))*kinNO3/(kinNO3+u(24));
fFeOOH = u(3)/(KFeOOH+u(3))*kinO2/(kinO2+u(1))*kinNO3/(kinNO3+u(24))*kinFeOH3/(kinFeOH3+u(2));
fSO4 = u(4)/(KSO4+u(4))*kinO2/(kinO2+u(1))*kinNO3/(kinNO3+u(24))*kinFeOH3/(kinFeOH3+u(2))*kinFeOOH/(kinFeOOH+u(3));
fomso = kinSO4/(kinSO4+u(4));
Sat_FeS = u(5)*u(6)/(KFeS*h_plus^2);    %saturation index of FeS
P_index1 = Pz1/Cx1;
P_index2 = Pz2/Cx2;
N_index1 = Ny1/Cx1;
N_index2 = Ny2/Cx2;

%reaction rates------------------------------------------------------------
Rc1 = kOM1*u(12);           %first pool rate
R1a = Rc1*fO2*25;           %OM oxidation
R2a = Rc1*fNO3;             %OM oxidation by NO3
R3a = Rc1*fFeOH3;           %OM oxidation by Fe(OH)3
R4a = Rc1*fFeOOH;           %OM oxidation by FeOOH
R5a = Rc1*fSO4;             %OM oxidation by SO4

Rc2 = kOM2*u(13);           %second pool rate
R1b = Rc2*fO2*25;           %OM oxidation
R2b = Rc2*fNO3;             %OM oxidation by NO3
R3b = Rc2*fFeOH3;           %OM oxidation by Fe(OH)3
R4b = Rc2*fFeOOH;           %OM oxidation by FeOOH
R5b = Rc2*fSO4;             %OM oxidation by SO4

R1 = R1a+R1b;
R2 = R2a+R2b;
R3 = R3a+R3b;
R4 = R4a+R4b;
R5 = R5a+R5b;

Ra = R1a+R2a+R3a+R4a+R5a;                   %degradation of OM1
Rb = R1b+R2b+R3b+R4b+R5b;                   %degradation of OM2

R6 = ktsox*u(1)*u(6);                   %S(II) oxidation by O2
R7 = ktsfe*u(2)*u(6);                   %Fe(OH)3 reduction by S2-
R8 = kfeox*u(1)*u(5);                   %Fe(II) oxidation by O2

if (Sat_FeS>=1)
    R9 = 0;
    R_9 = kfepre*(Sat_FeS-1);           %precipitation rate of FeS
else
    R9 = kfedis*u(7)*(1-Sat_FeS);       %dissolution rate of FeS
    R_9 = 0;
end

R10 = ksorg*u(6)*(u(12)+u(13));         %Sulfidization of OM
R11 = krhom*u(1)*u(7);                  %S8 formation
R12 = kpyrpre*u(6)*u(7);                %Pyrite precipitation
R13 = kSdis*u(9);                       %Elemental sulfur dissolution
R_13 = kSpre*u(8);                      %Elemental sulfur precipitation
R14 = komso*fomso;                      %OMSO hydrolysis
R15 = kOMS*u(4)*(Rc1+Rc2);              %Formation of OMS from SO4 directly
R16 = kAsO4_adsa*u(2)*u(18);            %As sorption onto Fe(OH)3
R17 = kAsO4_adsb*u(3)*u(18);            %As sorption onto FeOOH
R18 = kAs_FeS*u(7)*u(18);               %As sorption onto FeS
R19 = kAs_FeS2*u(10)*u(18);             %As sorption onto FeS2
R20 = fAsFe*(4*R3+2*R7);                %As release from Fe(OH)3
R21 = fAsFe*4*R4;                       %As release from FeOOH
R22 = k_psorb_a*u(2)*u(19);             %PO4 sorption onto Fe(OH)3
R23 = k_psorb_b*u(3)*u(19);             %PO4 sorption onto FeOOH
R24 = fPFe*(4*R3+2*R7);                 %PO4 release from Fe(OH)3
R25 = fPFe*4*R4;                        %PO4 release from FeOOH

if u(19)>kapa
    R26 = k_apa*(u(19)-kapa);           %Apatite precipitation
else
    R26 = 0;
end

R27 = knh4ox*u(1)*u(25);                %Nitrification

%constant porosity---------------------------------------------------------
c = ones(NumVars,1);%c

%depth dependant porosity
% c = [ phi;...
%       1-phi;...
%       phi;...
%       phi;...
%       phi;...
%       1-phi;...
%       phi;...
%       1-phi];

%Transport: constant porosity----------------------------------------------
f = [(D_bio+D_O2)*DuDx(1)-w*u(1);...
    D_bio*DuDx(2)-w*u(2);...
    D_bio*DuDx(3)-w*u(3);...
    (D_bio+D_SO4)*DuDx(4)-w*u(4);...
    (D_bio+D_Fe)*DuDx(5)-w*u(5);...
    (D_bio+D_H2S)*DuDx(6)-w*u(6);...
    D_bio*DuDx(7)-w*u(7);...
    (D_bio+D_S0)*DuDx(8)-w*u(8);...
    D_bio*DuDx(9)-w*u(9);...
    D_bio*DuDx(10)-w*u(10);...
    D_bio*DuDx(11)-w*u(11);...
    D_bio*DuDx(12)-w*u(12);...
    D_bio*DuDx(13)-w*u(13);...
    D_bio*DuDx(14)-w*u(14);...
	D_bio*DuDx(15)-w*u(15);...
	D_bio*DuDx(16)-w*u(16);...
	D_bio*DuDx(17)-w*u(17);...
	(D_bio+D_AsO4)*DuDx(18)-w*u(18);...
	(D_bio+D_PO4)*DuDx(19)-w*u(19);...
	D_bio*DuDx(20)-w*u(20);...
	D_bio*DuDx(21)-w*u(21);...
	(D_bio+D_Ca2)*DuDx(22)-w*u(22);...
	D_bio*DuDx(23)-w*u(23);...
	(D_bio+D_NO3)*DuDx(24)-w*u(24);...
	(D_bio+D_NH4)*DuDx(25)-w*u(25)];%f
	
	
% Transport:depth-dependant porosity
% f = [((D_bio+D_O2)*DuDx(1)-w*u(1))*phi+D_bio*Dphi*u(1);...
%     (D_bio*DuDx(2)-w*u(2))*(1-phi)-D_bio*Dphi*u(2);...
%     ((D_bio+D_SO4)*DuDx(3)-w*u(3))*phi+D_bio*Dphi*u(3);...
%     ((D_bio+D_Fe)*DuDx(4)-w*u(4))*phi+D_bio*Dphi*u(4);...
%     ((D_bio+D_H2S)*DuDx(5)-w*u(5))*phi+D_bio*Dphi*u(5);...
%     (D_bio*DuDx(6)-w*u(6))*(1-phi)-D_bio*Dphi*u(6);...
%     ((D_bio+D_AsO4)*DuDx(7)-w*u(7))*phi+D_bio*Dphi*u(7);...
%     (D_bio*DuDx(8)-w*u(8))*(1-phi)-D_bio*Dphi*u(8)];
 
 
%Reaction: constant porosity----------------------------------------------- 
s = [(BC0_O2-u(1))*alfax + (-2*R6-0.25*R8-2*R27) + (-R1-3*R11)*F;...        %the first part are all in unit of umol/cm3/yr
    R8/F + (-4*R3-2*R7);...                                                 %while the second part are all in unit of umol/g/yr
    -4*R4+4*R11;...                                                         %this is the basis of using the conversion factor F
    (BC0_SO4-u(4))*alfax + R6 + (-0.5*R5+R14-R15)*F;...                    
    (BC0_Fe-u(5))*alfax - R8 + (4*R3+4*R4+2*R7+R9-R_9)*F;...  
    (BC0_H2S-u(6))*alfax + (-R6-R12) + (0.5*R5-R7+R9-R_9-R10)*F;... 
    -R12/F + (-R9+R_9-4*R11);... 
    (BC0_S0-u(8))*alfax + (R7+R13-R_13)*F;...
    +4*R11-R13+R_13;...
    +R12/F;...
    +R10+R15;...
    -Ra;...
    -Rb;...
    -R14;...
	+R16+R18-R20;...
    +R17-R21;...
	+R19;...
	(BC0_AsO4-u(18))*alfax + (-R16-R17-R18-R19+R20+R21)*F;...
	(BC0_PO4-u(19))*alfax - 2*R26 + (-R22-R23+R24+R25+P_index1*Ra+P_index2*Rb)*F;...
	+R22-R24;...
	+R23-R25;...
	(BC0_Ca2-u(22))*alfax - 3*R26;...
	+R26/F;...
	(BC0_NO3-u(24))*alfax + R27 - 0.8*R2*F;...
	(BC0_NH4-u(25))*alfax - R27 + (N_index1*Ra+N_index2*Rb)*F];%s

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%BLOCK THREE%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function u0 = pdex1ic(~)                            %initial condition
global NumVars;
u0 = zeros(NumVars,1);%u0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%BLOCK FOUR%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [pl,ql,pr,qr] = pdex1bc(~,ul,~,ur,~)       %boundary condition
global BC0_O2 BC0_FeOH3 BC0_FeOOH BC0_SO4 BC0_Fe BC0_H2S BC0_FeS BC0_S0...
       BC0_S8 BC0_FeS2 BC0_OMS BC0_OM1 BC0_OM2 BC0_OMSO BC0_AsFea BC0_AsFeb...
       BC0_AsFe2 BC0_AsO4 BC0_PO4 BC0_PO4adsa BC0_PO4adsb BC0_Ca2 BC0_CaPO4...
       BC0_NO3 BC0_NH4 w F NumVars;

%Upper bounday: constant porosity------------------------------------------
pl = [ul(1)-BC0_O2;...
      BC0_FeOH3/F;...
      BC0_FeOOH/F;...
      ul(4)-BC0_SO4;...
      ul(5)-BC0_Fe;...
      ul(6)-BC0_H2S;...
      BC0_FeS/F;...
      ul(8)-BC0_S0;...
      BC0_S8/F;...
      BC0_FeS2/F;...
      BC0_OMS/F;...
      BC0_OM1/F;...
      BC0_OM2/F;...
      BC0_OMSO/F;...
	  BC0_AsFea/F;...
	  BC0_AsFeb/F;...
	  BC0_AsFe2/F;...
	  ul(18)-BC0_AsO4;...
	  ul(19)-BC0_PO4;...
	  BC0_PO4adsa/F;...
	  BC0_PO4adsb/F;...
	  ul(22)-BC0_Ca2;...
	  BC0_CaPO4/F;...
	  ul(24)-BC0_NO3;...
	  ul(25)-BC0_NH4];%pl

	  
%1 for solid, 0 for solute for both constant and depth-dependant porosity

%Upper bounday: exemple for depth-dependant porosity
%rhob=2;% dry density of the sediment
%   pl = [ul(1)-BC0_O2;...
%       BC0_FeOH3/rhob;...
%       ul(3)-BC0_SO4;...
%       ul(4)-BC0_Fe;...
%       ul(5)-BC0_H2S;...
%       BC0_FeS/rhob;...
%       BC0_AsFeOx/rhob;...
%       ul(8)-BC0_AsO4];

ql = [0;1;1;0;0;0;1;0;1;1;1;1;1;1;1;1;1;0;0;1;1;0;1;0;0];%ql

%Lower bounday: constant porosity------------------------------------------
pr = [w*ur(1);...
      w*ur(2);...
      w*ur(3);...
      w*ur(4);...
      w*ur(5);...
      w*ur(6);...
      w*ur(7);...
      w*ur(8);...
      w*ur(9);...
      w*ur(10);...
      w*ur(11);...
      w*ur(12);...
      w*ur(13);...
      w*ur(14);...
	  w*ur(15);...
	  w*ur(16);...
	  w*ur(17);...
	  w*ur(18);...
	  w*ur(19);...
	  w*ur(20);...
	  w*ur(21);...
	  w*ur(22);...
	  w*ur(23);...
	  w*ur(24);...
	  w*ur(25)];%pr

%Lower bounday: exemple for depth-dependant porosity  
% pr = [w*ur(1)*phi-D_bio*Dphi*ur(1);...
%       w*ur(2)*(1-phi)+D_bio*Dphi*ur(2);...
%       w*ur(3)*phi-D_bio*Dphi*ur(3);...
%       w*ur(4)*phi-D_bio*Dphi*ur(4);...
%       w*ur(5)*phi-D_bio*Dphi*ur(5);...
%       w*ur(6)*(1-phi)+D_bio*Dphi*ur(6);...
%       w*ur(7)*(1-phi)+D_bio*Dphi*ur(7);...
%       w*ur(8)*phi-D_bio*Dphi*ur(8)];
	  
qr = ones(NumVars,1);%qr
%----------------------------------------------------------------